Repository marsfoundation/sparklend-deployments, pull requests merged in 2023-06, with the labels that each got.

#7 test: Spark spell 05-25 additional testing [WIP]
  diffs/pre-Spark-Ethereum-rETH-Listing_post-Spark-Ethereum-rETH-Listing.md
  src/proposals/20230525/SparkEthereum_20230525.t.sol
  src/proposals/20230525/SparkGoerli_20230525.t.sol
  src/proposals/Interfaces.sol
  test/IntegrationTest.t.sol
Labels: Priority: Medium, Status: Ready for Review

#10 A first round of cleanup
  Makefile
  create-liquidations.sh
  deploy.sh
  init.sh
  script/CreateLiquidations.s.sol
  script/DeploySpark.s.sol
  script/SeedTestnet.s.sol
  script/input/1/config.json
  script/input/5/config.json
  seed-testnet.sh
Labels: Status: Approved, Priority: High

#8 Improving the README
  README.md
Labels: Priority: Low

#22 More Tidyup
  Makefile
Labels: Priority: Medium, Status: Work In Progress

#20 Removes the Reserves + Emode from the Deploy
  .github/workflows/test.yml
  Makefile
  foundry.toml
  script/DeploySpark.s.sol
  script/SparkConfigEngine.s.sol
  script/input/1/config.json
  script/input/1/d3m-spark.json
  script/input/5/config.json
  script/input/5/d3m-spark.json
  script/output/1/example-latest.json
  script/output/1/run-latest.json
  script/output/5/run-latest.json
  src/SavingsDaiOracle.sol
  src/SparkMigrationHelper.sol
  src/testnet/Faucet.sol
  test/DaiInterestRateStrategy.t.sol
  test/IntegrationTest.t.sol
  test/SparkDeployBase.t.sol
  test/SparkMigrationHelper.t.sol
  test/deploys/SparkDeploy_EthereumMain.t.sol
Labels: Priority: High, Status: Ready for Review

#23 More Refactoring to General to Multiple Instances
  Makefile
  README.md
  script/DeploySpark.s.sol
  script/DeploySparkConfigEngine.s.sol
  script/input/1/example.json
  script/input/1/primary.json
  script/input/1/spark-config-engine.json
  script/input/5/primary.json
  script/input/5/spark-config-engine.json
  script/output/1/primary-latest.json
  script/output/1/primary-sce-latest.json
  script/output/5/primary-latest.json
  script/output/5/primary-sce-latest.json
  test/SparkDeployBase.t.sol
  test/deploys/SparkDeploy_ExampleFork.t.sol
Labels: Priority: High, Status: Ready for Review

#25 Improve the deploy integration test
  script/input/1/example.json
  script/input/1/primary.json
  script/input/5/primary.json
  script/output/1/example-latest.json
  test/SparkDeployBase.t.sol
  test/deploys/SparkDeploy_EthereumPrimary.t.sol
  test/deploys/SparkDeploy_ExampleFork.t.sol
  test/deploys/SparkDeploy_GoerliPrimary.t.sol
Labels: Priority: High, Status: Ready for Review

#26 feat: Format deploy code
  script/DeploySpark.s.sol
  test/SparkDeployBase.t.sol
Labels: Priority: High, Status: Ready for Review

#28 Two Bugs with Deploy Script
  script/DeploySpark.s.sol
Labels: Priority: High, Status: Ready for Review
